name: natour21
description: Application for excursions

publish_to: 'none'

version: 1.1.6+3

environment:
  sdk: ">=2.12.0 <3.0.0"

# ---------------------------

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.15
  onesignal_flutter: ^3.5.0
  check_app_version: 1.0.0+1
  url_launcher: ^6.1.7
  http: ^0.13.5
  enum_to_string: ^2.0.1
  intl: ^0.17.0
  android_power_manager: ^1.0.0
  connectivity_plus: ^3.0.2

  cupertino_will_pop_scope: ^1.2.1
  ionicons: ^0.2.1
  flutter_custom_clippers: ^2.1.0
  keyboard_attachable: ^2.1.0
  flutter_slidable: ^2.0.0
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3
  crop_your_image: ^0.6.0+1
  flutter_advanced_drawer: ^1.3.2
  syncfusion_flutter_sliders: ^20.4.42
  flutter_rounded_date_picker: ^3.0.2
  easy_localization: ^3.0.1
  provider: ^6.0.5
  webview_flutter: ^4.0.1
  auto_animated: ^3.1.0
  flutter_animator: ^3.2.2
  tutorial_coach_mark: ^1.2.4
  readmore: ^2.2.0

  sign_in_with_apple: ^4.3.0

  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  gpx: ^2.2.1
  flutter_secure_storage: ^7.0.1

  firebase_analytics: ^10.1.0
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  flutter_facebook_auth: ^5.0.7
  google_sign_in: ^5.4.2
  fake_cloud_firestore: ^2.2.0

  amazon_cognito_identity_dart_2: ^3.1.1

  image_picker: ^0.8.6
  path_provider: ^2.0.11
  file_picker: ^5.2.4
  pdf: ^3.8.4
  web_socket_channel: ^2.2.0
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# ---------------------------

flutter:

  assets:
    - assets/images/
    - assets/images/markers/
    - assets/images/interest_point/
    - assets/images/category/m/
    - assets/images/category/p/
    - assets/images/category/c/
    - assets/translations/
    - assets/test/

  fonts:

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf

  uses-material-design: true

